---
- template: src={{ item }}.j2 dest=/{{ item }} backup=yes
  with_items:
    - etc/mongodb.conf
    - etc/ceilometer/ceilometer.conf

- service: name=mongodb state=stopped

- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed/ceilometer-01", command: "rm -f /var/lib/mongodb/journal/prealloc.*" }

- service: name=mongodb state=started

- wait_for: host=10.0.0.11 port=27017 delay=10

- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed/ceilometer-11", command: "mongo --host 10.0.0.11 --eval 'db = db.getSiblingDB(\"ceilometer\"); db.addUser({user: \"ceilometer\", pwd: \"{{ CEILOMETER_DBPASS }}\", roles: [ \"readWrite\", \"dbAdmin\" ]})'" }
    - { index: "~/.executed/ceilometer-12", command: "usermod -g ceilometer -G swift swift" }
    - { index: "~/.executed/ceilometer-13", command: "chown -R ceilometer:ceilometer /var/log/ceilometer" }
    - { index: "~/.executed/ceilometer-14", command: "chmod g=rxw /var/log/ceilometer" }
    - { index: "~/.executed/ceilometer-21", command: "sed -i 's,keystoneauth proxy-server,keystoneauth ceilometer proxy-server,g' /etc/swift/proxy-server.conf" }
    - { index: "~/.executed/ceilometer-22", command: "echo '[filter:ceilometer]' | sudo tee -a /etc/swift/proxy-server.conf" }
    - { index: "~/.executed/ceilometer-23", command: "echo 'use = egg:ceilometer#swift' | sudo tee -a /etc/swift/proxy-server.conf" }

- service: name={{ item }} state=restarted
  with_items: 
    - ceilometer-agent-central
    - ceilometer-agent-notification
    - ceilometer-api
    - ceilometer-collector
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
    - swift-proxy

