---
- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed/neutron-01", command: "cp /etc/sysctl.conf /etc/sysctl.conf.orig" }
    - { index: "~/.executed/neutron-02", command: "sed -i 's,net.ipv4.ip_forward.*,net.ipv4.ip_forward=1,g' /etc/sysctl.conf" }
    - { index: "~/.executed/neutron-03", command: "sed -i 's,net.ipv4.conf.all.rp_filter.*,net.ipv4.conf.all.rp_filter=0,g' /etc/sysctl.conf" }
    - { index: "~/.executed/neutron-04", command: "sed -i 's,net.ipv4.conf.default.rp_filter.*,net.ipv4.conf.default.rp_filter=0,g' /etc/sysctl.conf" }
    - { index: "~/.executed/neutron-05", command: "sed -i 's,^net.bridge,#net.bridge,g' /etc/sysctl.conf" }
    - { index: "~/.executed/neutron-06", command: "sysctl -p" }
  tags: neutron

- apt: name={{ item }} state=installed
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent
    - openvswitch-datapath-dkms
    - neutron-l3-agent
    - neutron-dhcp-agent
  tags: neutron

- template: src={{ item }}.j2 dest=/{{ item }} backup=yes
  with_items:
    - etc/neutron/dhcp_agent.ini
    - etc/neutron/l3_agent.ini
    - etc/neutron/metadata_agent.ini
    - etc/neutron/plugins/ml2/ml2_conf.ini
    - etc/neutron/neutron.conf

- service: name={{ item }} state=restarted
  with_items:
    - openvswitch-switch

- shell: "{{ item.command }} && touch {{ item.index }} creates={{ item.index }}"
  with_items:
    - { index: "~/.executed/neutron-11", command: "ovs-vsctl add-br br-int" }
    - { index: "~/.executed/neutron-12", command: "ovs-vsctl add-br br-ex" }
    - { index: "~/.executed/neutron-13", command: "ovs-vsctl add-port br-ex {{ INTERFACE_NAME }}" }
    - { index: "~/.executed/neutron-14", command: "ethtool -K {{ INTERFACE_NAME }} gro off" }

- service: name={{ item }} state=restarted
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
